version: v2beta1
name: edgefarm-applications

functions:
  wait_for_deployment: |-
    #!/bin/bash
    set -e
    echo "wait for deployment/$1 (ns: $2)"
    until kubectl wait --for=condition=available deployment/$1 -n $2 --timeout=60s 2>/dev/null; do echo -n "." && sleep 2; done

pipelines:
  deploy: |
    run_pipelines deploy-vela-core
    run_pipelines deploy-vela-caps

  deploy-vela-core: |-
    #!/bin/bash
    set -e
    create_deployments vela-system
    wait_for_deployment kubevela-cluster-gateway vela-system
    wait_for_deployment kubevela-vela-core vela-system

  deploy-vela-caps: |-
    #!/bin/bash
    set -e
    create_deployments vela-caps

deployments:
  vela-system:
    kubectl:
      kustomize: true
      kustomizeArgs: ["--enable-helm"]
      manifests:
        - ./manifests/vela-system
    namespace: vela-system

  vela-caps:
    kubectl:
      kustomize: true
      manifests:
        - ./manifests/vela-caps
    namespace: vela-system
