version: v2beta1
name: edgefarm-applications

commands:
  help: |-
    #!/bin/bash
    set -e
    GREEN='\033[0;32m'
    BRED='\033[3;31m'
    BGREEN='\033[1;32m'
    GREY='\033[0;36m'
    BOLD='\033[1m'
    NC='\033[0m' # No Color
    echo -e "${BGREEN}Usage of ${BRED}edgefarm.core:${NC}"
    echo -e "${GREEN} EdgeFarm related commands:${NC}"
    echo -e "${BOLD}  devspace run-pipeline deploy                    ${GREY}Deploy the edgefarm.applications stack${NC}"

functions:
  wait_for_deployment: |-
    #!/bin/bash
    set -e
    echo "wait for deployment/$1 (ns: $2)"
    until kubectl wait --for=condition=available deployment/$1 -n $2 --timeout=60s 2>/dev/null; do echo -n "." && sleep 2; done

pipelines:
  deploy: |
    run_pipelines deploy-vela-core
    run_pipelines deploy-vela-caps

  deploy-vela-core: |-
    #!/bin/bash
    set -e
    create_deployments vela-system
    wait_for_deployment kubevela-cluster-gateway vela-system
    wait_for_deployment kubevela-vela-core vela-system

  deploy-vela-caps: |-
    #!/bin/bash
    set -e
    create_deployments vela-caps

deployments:
  vela-system:
    kubectl:
      kustomize: true
      kustomizeArgs: ["--enable-helm"]
      manifests:
        - ./manifests/vela-system
    namespace: vela-system

  vela-caps:
    kubectl:
      kustomize: true
      manifests:
        - ./manifests/vela-caps
    namespace: vela-system
