apiVersion: k3d.io/v1alpha3
kind: Simple
name: edgefarm-applications
servers: 1
agents: 1
kubeAPI:
  hostPort: "40550"
image: rancher/k3s:v1.20.12-k3s1
registries:
  use:
    - registry.k3d.localhost:5000
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      # set admission plugins (e.g. for capsule)
      - arg: --kube-apiserver-arg=enable-admission-plugins=PodNodeSelector,LimitRanger,ResourceQuota,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
        nodeFilters:
          - server:*
ports:
  - port: 40080:80
    nodeFilters:
      - loadbalancer
  - port: 40443:443
    nodeFilters:
      - loadbalancer
  - port: 40000:10000
    nodeFilters:
      - server:*
  - port: 40002:10002
    nodeFilters:
      - server:*
  - port: 40003:10003
    nodeFilters:
      - server:*
  - port: 40004:10004
    nodeFilters:
      - server:*
