apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: mixed-app-network
  namespace: test
spec:
  components:
    - name: cloud-application1
      type: main-worker
      properties:
        image: nginx
        name: simplenginx
      traits:
        - type: labels
          properties:
            "app": "cloud-application1"
        - type: network-participant
          properties:
            network: mixed-app-network
    - name: edge-application1
      type: edge-worker
      properties:
        image: nginx
        name: simplenginx
      traits:
        - type: labels
          properties:
            "app": "edge-application1"
        - type: network-participant
          properties:
            network: mixed-app-network
    - name: edge-application2
      type: edge-worker
      properties:
        image: nginx
        name: simplenginx
      traits:
        - type: labels
          properties:
            "app": "edge-application2"
        - type: network-participant
          properties:
            network: mixed-app-network
    - type: application-network
      name: mixed-app-network
      properties:
        streams:
          - name: myStream1
            subjects:
              - stream1SubjectA
            storage: file
          - name: myStream2
            subjects:
              - stream2SubjectA
              - stream2SubjectB
            storage: file
