apiVersion: v1
kind: Namespace
metadata:
  name: nats-box
---
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: nats-box
  namespace: nats-box
spec:
  components:
    - name: nats-box-edge
      type: edge-worker
      properties:
        image: natsio/nats-box:latest
        name: nats-box
        command:
          - /bin/sh
          - -c
          - --
        args:
          - "while true; do sleep 1; done;"
        ports:
          - name: nats-box
            hostPort: 8080
            containerPort: 80
            protocol: TCP

      traits:
        - type: edge-network-participant
          properties:
            networks:
              - nats-box-network

    - name: nats-box-cloud
      type: cloud-worker
      properties:
        image: natsio/nats-box:latest
        name: nats-box
        command:
          - /bin/sh
          - -c
          - --
        args:
          - 'apk add curl; while true; do for i in {1..10000}; do curl -X POST http://localhost:3501/v1.0/publish/nats-box-network/data -H "Content-Type: application/json" -d ''{"hallo ihr da": "100"}''; done; sleep 1; done;'
      traits:
        - type: cloud-network-participant
          properties:
            networks:
              - nats-box-network

    - type: application-network
      name: nats-box-network
      properties:
        streams:
          - name: data
            subjects:
              - data
            storage: file
