apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: mixed-app-network-volume
spec:
  components:
    - name: cloud-application1
      type: main-worker
      properties:
        image: nginx
        name: simplenginx
      traits:
        - type: labels
          properties:
            "app": "cloud-application1"
    - name: edge-application1
      type: edge-worker
      properties:
        image: nginx
        name: simplenginx
        volumes:
          - name: "edge-application1-volume"
            mountPath: "/mountedPath"
            volumeType: "hostPath"
            hostPath:
              path: "/tmp/edge-application1-volume"
          - name: "edge-application1-volume-second"
            mountPath: "/mountedOtherPath"
            volumeType: "hostPath"
            hostPath:
              path: "/tmp/edge-application1-volume-second"
      traits:
        - type: labels
          properties:
            "app": "edge-application1"

    - name: edge-application2
      type: edge-worker
      properties:
        image: nginx
        name: simplenginx
      traits:
        - type: labels
          properties:
            "app": "edge-application2"
