apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: mixed-app
spec:
  components:
    - name: cloud-application1
      type: main-worker
      properties:
        image: nginx
        name: simplenginx
      traits:
        - type: labels
          properties:
            "app": "cloud-application1"
    - name: edge-application1
      type: edge-worker
      properties:
        image: nginx
        name: simplenginx
      traits:
        - type: labels
          properties:
            "app": "edge-application1"
    - name: edge-application2
      type: edge-worker
      properties:
        image: nginx
        name: simplenginx
      traits:
        - type: labels
          properties:
            "app": "edge-application2"
