# yaml-language-server: https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: vela-core
    namespace: vela-system
    version: 1.8.2
    repo: https://charts.kubevela.net/core
    releaseName: kubevela
    includeCRDs: true
    # valuesInline:
    #   admissionWebhooks:
    #     certManager:
    #       enabled: true
