apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: myapp
spec:
  components:
    - name: myapp
      type: edgefarm-applications
      properties:
        image: natsio/nats-box:latest
        nodepoolSelector:
          matchLabels:
            mynetwork-big: ""
        name: myapp
        command:
          - sh
          - "-c"
          - "sleep infinity"
        tolerations:
          - key: "edgefarm.io"
            operator: "Exists"
            effect: "NoSchedule"
      traits:
        - type: edgefarm-network
          properties:
            network:
              name: mynetwork
              subnetwork: big
              user: bigonly
