######################################
# delete all TraitDefinitions
######################################
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: affinity
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: annotations
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: command
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: configmap
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: container-image
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: cpuscaler
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: env
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: expose
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: gateway
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: hostalias
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: hpa
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: ingress
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: ingress-1-20
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: init-container
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: json-merge-patch
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: json-patch
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: k8s-update-strategy
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: labels
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: lifecycle
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: nocalhost
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: node-affinity
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: pure-ingress
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: pvc
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: resource
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: scaler
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: service-account
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: service-binding
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: sidecar
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: startup-probe
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: storage
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: topologyspreadconstraints
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  namespace: vela-system
  name: volumes
######################################
# delete all WorkflowStepDefinitions
######################################
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: apply-application
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: apply-application-in-parallel
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: apply-component
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: apply-deployment
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: apply-object
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: apply-remaining
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: apply-terraform-config
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: apply-terraform-provider
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: build-push-image
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: check-metrics
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: clean-jobs
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: collect-service-endpoints
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: create-config
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: delete-config
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: depends-on-app
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: deploy
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: deploy-cloud-resource
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: deploy2env
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: deploy2runtime
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: export-data
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: export-service
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: export2config
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: export2secret
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: generate-jdbc-connection
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: list-config
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: notification
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: print-message-in-status
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: read-config
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: read-object
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: request
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: share-cloud-resource
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: step-group
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: suspend
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: vela-cli
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkflowStepDefinition
metadata:
  namespace: vela-system
  name: webhook
######################################
# delete all WorkloadDefinitions
######################################
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: WorkloadDefinition
metadata:
  namespace: vela-system
  name: autodetects.core.oam.dev
# ---
# $patch: delete
# apiVersion: core.oam.dev/v1beta1
# kind: WorkloadDefinition
# metadata:
#   namespace: vela-system
#   name: daemonsets.apps
# ---
# $patch: delete
# apiVersion: core.oam.dev/v1beta1
# kind: WorkloadDefinition
# metadata:
#   namespace: vela-system
#   name: deployments.apps
# ---
# $patch: delete
# apiVersion: core.oam.dev/v1beta1
# kind: WorkloadDefinition
# metadata:
#   namespace: vela-system
#   name: jobs.batch
######################################
# delete all ComponentDefinitions
######################################
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  namespace: vela-system
  name: cron-task
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  namespace: vela-system
  name: daemon
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  namespace: vela-system
  name: k8s-objects
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  namespace: vela-system
  name: raw
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  namespace: vela-system
  name: ref-objects
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  namespace: vela-system
  name: task
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  namespace: vela-system
  name: webservice
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  namespace: vela-system
  name: worker
######################################
# delete all PolicyDefinitions
######################################
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: PolicyDefinition
metadata:
  namespace: vela-system
  name: apply-once
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: PolicyDefinition
metadata:
  namespace: vela-system
  name: envbinding
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: PolicyDefinition
metadata:
  namespace: vela-system
  name: garbage-collect
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: PolicyDefinition
metadata:
  namespace: vela-system
  name: health
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: PolicyDefinition
metadata:
  namespace: vela-system
  name: override
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: PolicyDefinition
metadata:
  namespace: vela-system
  name: read-only
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: PolicyDefinition
metadata:
  namespace: vela-system
  name: replication
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: PolicyDefinition
metadata:
  namespace: vela-system
  name: shared-resource
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: PolicyDefinition
metadata:
  namespace: vela-system
  name: take-over
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: PolicyDefinition
metadata:
  namespace: vela-system
  name: topology
######################################
# delete all ScopeDefinitions
######################################
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: ScopeDefinition
metadata:
  name: healthscopes.core.oam.dev
  namespace: vela-system
######################################
# delete all Applications
######################################
---
$patch: delete
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    helm.sh/hook: test-success
    helm.sh/hook-delete-policy: hook-succeeded
  name: helm-test-vela-app
  namespace: vela-system
