apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: cloud-app
spec:
  components:
    - name: cloud-application1
      type: main-worker
      properties:
        image: nginx
        name: simplenginx
      traits:
        - type: labels
          properties:
            "release": "stable"
