apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: edge-app-network
spec:
  components:
    - name: edge-application1
      type: edge-worker
      properties:
        image: nginx
        name: simplenginx
        runtime:
          - mynode
          - cheesebread
      traits:
        - type: labels
          properties:
            "app": "edge-application1"
    - name: network
      type: application-network
      properties:
        usernames:
          - edge-application1
