# yaml-language-server: https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: edge-app

resources:
  - "./edge-app.yaml"
  - "./edge-app-network.yaml"
  - "./edge-app-network-no-runtimes.yaml"
